### ISSUE TITLE
Gatekeeper vulnerable to recently announced Node.js security vulnerability

### ISSUE THREAD

**Issue by compumike08** [prose/gatekeeper#32]
Node.js recently announced a severe security vulnerability (see [here](https://nodejs.org/en/blog/vulnerability/july-2017-security-releases/)), and they recommend upgrading to a patched version of Node.js immediately. Heroku is instructing people to make sure that their "engines.node.version" value in their `package.json` files is set to a specific version which is patched (see [here](https://kb.heroku.com/node-js-constant-hashtable-seeds-vulnerability-faq)).

Gatekeeper's current "engines.node.version" value in its `package.json` value needs to be changed to specify a specific patched version to avoid this security vulnerability.

See PR: #31

**Comment by dereklieu** [comment]
Merged and deployed with Node ~6.11.1
