### ISSUE TITLE
[V1] Add tests

### ISSUE THREAD

**Issue by kriswep** [prose/gatekeeper#40]
We need a sufficient enough test suite to be able to be confident about future refactors.

The test framework / runner needs to be discussed.

[tape](https://github.com/substack/tape) was mentioned, which is known to be a quite lightweight solution. However, in my opinion, adding things like mock suppport needs more configuration to work.

I also would like to add [jest](https://facebook.github.io/jest/) to the discussion, which is more a batteries included solution. Nice features are integrated snapshot testing (good for APIs), mocking and a quick interactive watch mode.

More opinions on test runners/framework welcome.

Also desirable would be some kind of CI setup, eg [travis](travis-ci.org/)

**Comment by kriswep** [comment]
as a reference I added a first test suite implementation in #44.

**Comment by dereklieu** [comment]
Thanks @kriswep. Let's ticket out additional test coverage requests/to-dos separately.
